### PR TITLE
fix coverage for forked processes

### LINKED ISSUE #433: does forking in tests affect correctness of coverage repors?
@kr said in #431: "Note that this change doesn't prevent forking, it just limits the number of tests to one at a time." and

> The two fork calls I know of of the top of my head are:
> 
> * https://github.com/beanstalkd/beanstalkd/blob/5c01de1acdc4129bbfc74e875dd67fdd09370436/ct/ct.c#L197
> * https://github.com/beanstalkd/beanstalkd/blob/5c01de1acdc4129bbfc74e875dd67fdd09370436/testserv.c#L43
> 
> I do not expect it to be trivial to remove either of them.

It means that we need to investigate if forking affects the coverage correctness.

### PR DESCRIPTION
**Pull request by ysmolsky**
Previously, the forked process with a server was killed by SIGKILL. 
This prevented the process from writing coverage data.

This patch enables the child processes to handle the SIGUSR2 signal.
testserv.c setups a handler that flushes coverage data prior exiting.
This handler is setup only when WITHCOV is defined in CFLAGS.

Coverage after the patch:

lines: 64.9% (1434 out of 2209)
branches: 50.9% (649 out of 1274)

Updates #424
Fixes #433

### CODE REVIEW

**Comment by kr** [comment]
Can I suggest using `SIGTERM` here instead, since we want the process to terminate.

File: testserv.c [hunk 1]
```diff
@@ -87,12 +86,43 @@ mustdiallocal(int port)
...
 }
 
-#define SERVER() (progname = __func__, mustforksrv())
+#ifdef WITHCOV
+void __gcov_flush (void);
+
+void
+gcov_flush(int signum)
+{
+    __gcov_flush(); /* dump coverage data  */
```
Comment (kr) [inline testserv.c]: No need to call `__gcov_flush` here. Instead we can call `exit` and let gcov's atexit handler flush.

It's better not to call gcov internals directly if we can avoid it, and in this case we can.

File: testserv.c [hunk 2]
```diff
@@ -87,12 +86,43 @@ mustdiallocal(int port)
...
+    usleep(500000); /* .5s; time to write data */
+    exit(1);        /* some tests are stuck without it */
```
Comment (kr) [inline testserv.c]: Why not `exit(0)`?

File: testserv.c [hunk 3]
```diff
@@ -202,18 +236,14 @@ readline(int fd)
 static void
 ckresp(int fd, char *exp)
 {
-    char *line;
-
-    line = readline(fd);
+    char *line = readline(fd);
```
Comment (kr) [inline testserv.c]: There are quite a few unrelated changes in this PR, such as the one on this line. What do you think about making those separately?

File: testserv.c [hunk 4]
```diff
@@ -123,6 +153,9 @@ mustforksrv()
     /* now in child */
 
     prot_init();
+#ifdef WITHCOV
```
Comment (kr) [inline testserv.c]: I think it's reasonable to install the signal handler unconditionally, especially if it uses `SIGTERM`.

File: ct/ct.c [hunk 5]
```diff
@@ -167,7 +167,7 @@ waittest(Test *ts)
     if (pid == -1) {
         die(3, errno, "wait");
     }
-    killpg(pid, 9);
+    killpg(pid, SIGUSR2);
```
Comment (kr) [inline ct/ct.c]: I'd suggest `SIGTERM` here, since this is a pretty ordinary "kill the process, but let it do something before it exits" situation.

Comment (kr) [reply ct/ct.c]: Considering https://github.com/beanstalkd/beanstalkd/issues/424#issuecomment-509476476, maybe we could avoid making any patch to ct here. That might be preferable, since it'll make updating ct easier in the future.

**Comment by ysmolsky** [comment]
@kr thanks for the help. I will look into your comments and adopt suggestions.

File: testserv.c (hunk 3 above)
Comment (ysmolsky) [reply testserv.c]: I agree. I tend to add additional style improvements but i think it makes sense to not touch it here.

File: testserv.c (hunk 4 above)
Comment (ysmolsky) [reply testserv.c]: I was meaning to use SIGTERM too because I think that this case should be handled as generally as possible.

File: ct/ct.c (hunk 5 above)
Comment (ysmolsky) [reply ct/ct.c]: I have tried this approach with atexit, but it leads to some tests failed. These tests kill child-server in the middle of test and then the controlling wrapper thinks that since the test has received SIGTERM (15), it has failed:
```
ct/_ctcheck
................E...EE........................................

cttest_binlog_basic: error (signal 15)
start server port=55911 pid=86446
>20 put 0 0 100 0
>20
<20 INSERTED 1
start server port=55913 pid=86447
>22 delete 1
<22 DELETED

cttest_binlog_empty_exit: error (signal 15)
start server port=55921 pid=86455
start server port=55922 pid=86456
>25 put 0 0 0 0
>25
<25 INSERTED 1

cttest_binlog_read: error (signal 15)
start server port=55924 pid=86458
>25 use test
<25 USING test
>25 put 0 0 120 4
>25 test
<25 INSERTED 1
>25 put 0 0 120 4
>25 tes1
<25 INSERTED 2
>25 watch test
<25 WATCHING 2
>25 reserve
<25 RESERVED 1 4
<25 test
>25 release 1 1 1
<25 RELEASED
>25 reserve
<25 RESERVED 2 4
<25 tes1
>25 delete 2
<25 DELETED
start server port=55926 pid=86459
>27 watch test
<27 WATCHING 2
>27 reserve
<27 RESERVED 1 4
<27 test
>27 delete 1
<27 DELETED
>27 delete 2
<27 NOT_FOUND

0 failures; 3 errors.
make: *** [check] Error 1
lines: 62.3% (1392 out of 2236)
```

Alternatively,

We can skip everything in this patch if we change `ct.c` to `killpg(pid, SIGTERM)`. Or did the SIGKILL (9) exist because of cleanup reasons? Then I tried this, all tests were cleanup properly. Did you have something in mind when you used SIGKILL (9) in ct.c?

Comment (ysmolsky) [reply ct/ct.c]: > We can skip everything in this patch if we change ct.c to killpg(pid, SIGTERM). Or did the SIGKILL (9) exist because of cleanup reasons? Then I tried this, all tests were cleanup properly. Did you have something in mind when you used SIGKILL (9) in ct.c?

I take it back. It was the uncleaned cache of coverage data that made me to think that. It is not enough to change to SIGTERM.

**Comment by ysmolsky** [comment]
@kr I have stuck with the solution proposed. Please see tests output, to which I have added some debugging prints. I am confused how the tests are run when we make two calls to SERVER() in one test. I guess some fork there does not do what is expected by testing framework. Please look at this and let me know. I am puzzled. I do want to solve it your way.

Output: https://travis-ci.org/beanstalkd/beanstalkd/jobs/556449326
```
ct/_ctcheck
................E...EE........................................
cttest_binlog_basic: error (signal 15)
start server port=46526 pid=5292
>22 put 0 0 100 0
>22 
<22 INSERTED 1
exiting from child
start server port=46084 pid=5293
>24 delete 1
<24 DELETED
exiting from child
killing 0
waiting 0
exited 0
cttest_binlog_empty_exit: error (signal 15)
start server port=42929 pid=5301
start server port=42870 pid=5302
>27 put 0 0 0 0
>27 
<27 INSERTED 1
start server port=42929 pid=5301
exiting from child
killing 0
waiting 0
exited 0
cttest_binlog_read: error (signal 15)
start server port=43778 pid=5304
>27 use test
<27 USING test
>27 put 0 0 120 4
>27 test
<27 INSERTED 1
>27 put 0 0 120 4
>27 tes1
<27 INSERTED 2
>27 watch test
<27 WATCHING 2
>27 reserve
<27 RESERVED 1 4
<27 test
>27 release 1 1 1
<27 RELEASED
>27 reserve
<27 RESERVED 2 4
<27 tes1
>27 delete 2
<27 DELETED
exiting from child
start server port=45984 pid=5305
>29 watch test
<29 WATCHING 2
>29 reserve
<29 RESERVED 1 4
<29 test
>29 delete 1
<29 DELETED
>29 delete 2
<29 NOT_FOUND
exiting from child
killing 0
waiting 0
exited 0
0 failures; 3 errors.
```

**Comment by ysmolsky** [comment]
@kr I have uploaded the corresponding code and another commit, you might want to look at it.

**Comment by ysmolsky** [comment]
I think I got it. After debugging I see that first fork in SERVER() makes some weird not needed atexit kill. Since the first SERVER() fork is being explicitly killed in the test, we can omit setting up atexit in first SERVER(), but in the second SERVER() we should keep it. Preparing the patch...

File: testserv.c (hunk 1 above)
Comment (ysmolsky) [reply testserv.c]: Done

File: testserv.c (hunk 2 above)
Comment (ysmolsky) [reply testserv.c]: yes, 0 is good enough.

**Comment by ysmolsky** [comment]
Patch is done. @kr, please take a look.

File: testserv.c [hunk 6]
```diff
@@ -670,9 +705,9 @@ cttest_binlog_empty_exit()
     srv.wal.use = 1;
     job_data_size_limit = 10;
 
-    port = SERVER();
+    port = SERVER_NO_ATEXIT();
 
-    kill(srvpid, 9);
+    kill(srvpid, SIGTERM);
```
Comment (kr) [inline testserv.c]: Good catch. 👍

File: testserv.c [hunk 7]
```diff
@@ -87,12 +87,47 @@ mustdiallocal(int port)
...
+// to write gcov data to the filesystem before ct kills it with SIGKILL.
+static void
+kill_srv_atexit(void)
+{
+    kill(srvpid, SIGTERM);
+    waitpid(srvpid, 0, 0);
+}
+
+#define SERVER() (progname=__func__, mustforksrv(true))
+#define SERVER_NO_ATEXIT() (progname=__func__, mustforksrv(false))
```
Comment (kr) [inline testserv.c]: I wonder if it would be any better to test if srvpid is nonzero in kill_srv_atexit, so that we can install the atexit function unconditionally.

```c
static void
kill_srv_atexit(void)
{
    if (srvpid == 0) {
        return;
    }
    kill(srvpid, SIGTERM);
    waitpid(srvpid, 0, 0);
    srvpid = 0;
}
```

I think this logic would make it safe & okay for kill_srv_atexit to be registered two or more times.

(In that case it might also make sense to extract those last three lines into a helper function so it can be used in tests like cttestbinlogemptyexit.)

Just a thought. The `SERVER_NO_ATEXIT` approach is okay with me too.

Comment (ysmolsky) [reply testserv.c]: Very good observation!
