### PR TITLE
use size_t for indexes in the heap structure

### LINKED ISSUE #443: Makefile: add -Wextra flag and fix errors
To make compiler more strict we can add `-Wextra` and fix these errors:
```
~/d/beanstalkd (master *%=) % make -k
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o conn.o conn.c
conn.c:17:13: error: unused parameter 'a' [-Werror,-Wunused-parameter]
on_watch(ms a, tube t, size_t i)
            ^
conn.c:17:31: error: unused parameter 'i' [-Werror,-Wunused-parameter]
on_watch(ms a, tube t, size_t i)
                              ^
conn.c:24:14: error: unused parameter 'a' [-Werror,-Wunused-parameter]
on_ignore(ms a, tube t, size_t i)
             ^
conn.c:24:32: error: unused parameter 'i' [-Werror,-Wunused-parameter]
on_ignore(ms a, tube t, size_t i)
                               ^
4 errors generated.
make: *** [conn.o] Error 1
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o file.o file.c
file.c:204:30: error: comparison of integers of different signs: 'int32' (aka 'int') and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
            if (jr.body_size > job_data_size_limit) {
                ~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~
file.c:328:30: error: comparison of integers of different signs: 'int32' (aka 'int') and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
            if (jr.body_size > job_data_size_limit) {
                ~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~
file.c:463:11: error: comparison of integers of different signs: 'int' and 'unsigned long' [-Werror,-Wsign-compare]
    if (n < sizeof(int)) {
        ~ ^ ~~~~~~~~~~~
3 errors generated.
make: *** [file.o] Error 1
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o heap.o heap.c
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o job.o job.c
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o ms.o ms.c
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o net.o net.c
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o primes.o primes.c
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o prot.o prot.c
prot.c:873:39: error: missing field 'ru_maxrss' initializer [-Werror,-Wmissing-field-initializers]
    struct rusage ru = {{0, 0}, {0, 0}};
                                      ^
prot.c:1199:24: error: comparison of integers of different signs: 'unsigned long' and 'int' [-Werror,-Wsign-compare]
    if (strlen(c->cmd) != c->cmd_len - 2) {
        ~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~
prot.c:1557:23: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
        for (i = 0; i < c->watch.used; i++) {
                    ~ ^ ~~~~~~~~~~~~~
prot.c:1650:22: error: unused parameter 'sig' [-Werror,-Wunused-parameter]
enter_drain_mode(int sig)
                     ^
prot.c:1878:19: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
    for (i = 0; i < tubes.used; i++) {
                ~ ^ ~~~~~~~~~~
prot.c:1908:36: error: unused parameter 'which' [-Werror,-Wunused-parameter]
h_accept(const int fd, const short which, Server *s)
                                   ^
6 errors generated.
make: *** [prot.o] Error 1
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o sd-daemon.o sd-daemon.c
sd-daemon.c:46:23: error: unused parameter 'unset_environment' [-Werror,-Wunused-parameter]
int sd_listen_fds(int unset_environment) {
                      ^
sd-daemon.c:327:19: error: unused parameter 'unset_environment' [-Werror,-Wunused-parameter]
int sd_notify(int unset_environment, const char *state) {
                  ^
sd-daemon.c:327:50: error: unused parameter 'state' [-Werror,-Wunused-parameter]
int sd_notify(int unset_environment, const char *state) {
                                                 ^
sd-daemon.c:395:20: error: unused parameter 'unset_environment' [-Werror,-Wunused-parameter]
int sd_notifyf(int unset_environment, const char *format, ...) {
                   ^
sd-daemon.c:395:51: error: unused parameter 'format' [-Werror,-Wunused-parameter]
int sd_notifyf(int unset_environment, const char *format, ...) {
                                                  ^
5 errors generated.
make: *** [sd-daemon.o] Error 1
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o serv.o serv.c
serv.c:12:5: error: missing field 'use' initializer [-Werror,-Wmissing-field-initializers]
    },
    ^
serv.c:13:1: error: missing field 'sock' initializer [-Werror,-Wmissing-field-initializers]
};
^
2 errors generated.
make: *** [serv.o] Error 1
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o time.o time.c
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o tube.o tube.c
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o util.o util.c
./verc.sh >vers.c
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o vers.o vers.c
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o walg.o walg.c
walg.c:391:27: error: unused parameter 'j' [-Werror,-Wunused-parameter]
walresvupdate(Wal *w, job j)
                          ^
1 error generated.
make: *** [walg.o] Error 1
cc -Wall -Werror -Wextra -Wformat=2 -g   -c -o main.o main.c
main.c:72:10: error: unused parameter 'argc' [-Werror,-Wunused-parameter]
main(int argc, char **argv)
         ^
1 error generated.
make: *** [main.o] Error 1
make: Target `all' not remade because of errors.
```

### PR DESCRIPTION
**Pull request by ysmolsky**
Previously "int" was used, it may be too small on some architectures.
This change uses "size_t" instead, since index cannot be negative.

In the heapremove function it removes the assignment to the heap_index
field of deleted member.

As usual in affected functions, I have moved  declarations of variables close
to their usage.

Updates #443

### CODE REVIEW

File: heap.c [hunk 1]
```diff
@@ -101,19 +97,18 @@ heapinsert(Heap *h, void *x)
...
     }
 
-    x = h->data[k];
+    void *x = h->data[k];
     h->len--;
     set(h, k, h->data[h->len]);
     siftdown(h, k);
     siftup(h, k);
-    h->rec(x, -1);
+    // (ysmolsky) Remove this? It's not being used anywhere except tests.
```
Comment (kr) [inline heap.c]: Removing it is fine by me.
